### ISSUE TITLE
Add ability to sign individual files

### ISSUE THREAD

**Issue by Lindsay-Mathieson** [dlemstra/code-sign-action#11]
I'm building a project that pulls in large numbers of third-party files that are already signed, I definitely shouldn't (edited) be adding our signature.

Currently working round this by moving our files to a temp directory and signing them there, but it would be nice if we could specifiy multiple files to sign rather than everything in a path.

**Comment by dlemstra** [comment]
Any ideas on how you would want to add that to the configuration of this action?

**Comment by Lindsay-Mathieson** [comment]
An optional files: attribute that takes comma separated file paths?

e.g

```
runs-on: windows-latest
steps:
  uses: dlemstra/code-sign-action@v1
  with:
    certificate: '${{ secrets. CERTIFICATE }}'
    password: '${{ secrets.CERTIFICATE_PASSWORD }}'
    files: 'MyProg.exe', 'MyDLL.dll'
```
